#!/usr/bin/env bash

VERSION=${DOCKER_COMPOSE_VERSION:-1.3.1}

binaryName="docker-compose-`uname -s`-`uname -m`"

curl -L https://github.com/docker/compose/releases/download/$VERSION/$binaryName > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

exit 0
